added warmup
AnastasiiaYaitska/hyf-homework pull request #21
Opened 2023-05-12 20:16 UTC by AnastasiiaYaitska

2023-05-14 12:07 UTC, te-online requested changes
Good work 👍 

- ✅ You created all the endpoints that were required
- ✅ You added case-insensitive search by using the `q` parameter
- ⚠️ You didn't allow `q` and `fields` to be provided at the same time
- ⚠️ Your fields search algorithm could either be simplified or made case-insensitive
- 💅 You could improve variable naming

2023-05-14 12:07 UTC, te-online commented on nodejs/week2/warmup/app.js
> +      const filteredDoc = documents.filter((doc) => {
The variable name `filteredDoc` indicates you're assigning just a single document to it, but in reality it's an array, right? What if we would find a better name for the variable?

2023-05-14 12:07 UTC, te-online commented on nodejs/week2/warmup/app.js
> +        res.status(404).send("Document not found");
In context of the search always returning an array, maybe we could find a better error message instead?

2023-05-14 12:07 UTC, te-online commented on nodejs/week2/warmup/app.js
> +      res.status(400).send("Query parameter and data can't be provided");
Should we be able to combine `q` and `fields`? Why did you decide to make them exclusive?

2023-05-14 12:07 UTC, te-online commented on nodejs/week2/warmup/app.js
> +          return doc[key] === fields[key] && doc[value] === fields[value];
Your `q` search is case-insensitive, but the `fields` search has to match exactly.

- If you want to match exactly the field, why not use `doc[fields[key]] === fields[value]`?
- If you want it to be case-insensitive, you'd have to add that functionality

2023-05-14 12:07 UTC, te-online commented on nodejs/week2/warmup/app.js
> +      if (document) {
Also here, the naming could be improved 🙂

2023-05-14 12:07 UTC, te-online commented on nodejs/week2/warmup/app.js
> +        res.send(document);
It doesn't look like you're taking the `q` value into account at all? 🤓

2023-05-25 10:48 UTC, AnastasiiaYaitska commented on nodejs/week2/warmup/app.js
> +        res.send(document);
Thank you Thomas!! ☺️ Can you take a look now?

2023-05-26 08:03 UTC, AnastasiiaYaitska commented on nodejs/week2/warmup/app.js
> +        res.send(document);
Thank you Thomas!!☺️ Canyou takea. look now?

2023-05-28 12:32 UTC, closed without merging

2023-05-28 17:27 UTC, te-online commented on nodejs/week2/warmup/app.js
> +        res.send(document);
I think you addressed all comments, but this one you skipped? 😊 `q` is still not being used in the code for this route, as far as I can see?